name: E2E Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      postgres:
        image: postgres:12.1-alpine
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
          POSTGRES_DB: test_db
        ports:
          - "5432:5432"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose -f docker-compose.yml up -d --build

      - name: Wait for services
        run: |
          docker compose exec -T auth python -m app.wait_for_db
          docker compose exec -T kafka cub kafka-ready -b kafka:9092 1 40

      - name: Run E2E tests
        run: docker compose -f docker-compose.yml run --rm e2e-tests